### ISSUE TITLE
Setup Serverpod deployment

### ISSUE THREAD

**Issue by krolmic** [krolmic/tracking_app#10]
## Tasks

- [x] Setup Serverpod deployment via Terraform & AWS
  - [x] Configure aws & terraform CLI
  - [x] Register domain
  - [x] Setup Route 53
  - [x] Configure Github
  - [x] Configure Serverpod
  - [x] Deploy infrastructure
  - [x] Create database tables
  - [x] Deploy & test production server 

- [x] Adapt Flutter app's code - read API host from env. variable (passed by e.g. dart define) 

- [x] Configure API Access Keys
  - [ ] Adapt Serverpod's code - read & verify the key in authentication (Serverpod.instance.passwords)
  - [x] Configure API variables for actions
  - [x] Adapt Flutter app's code - read from env. & use the key  to authenticate in API initialisation
  - [x] Test API key for development by app's client
  - [x] Deploy Serverpod changes for production
  - [x] Test API key for production by app's client

## Links

https://docs.serverpod.dev/deployments/deploying-to-aws
