### ISSUE TITLE
Track today's revenue and working hours

### ISSUE THREAD

**Issue by krolmic** [krolmic/tracking_app#11]
## User story

A s a user, additionally to my mood, things I'm grateful for and diary I am able to already track I would like to track my revenue and working hours.

### Aditional notes

Things related to my work can be tracked optionally. The app focuses on freelancers and people running a business in first place, but the long-term vision is to offer tracking other things that may be connected to users' mood e.g. sport sessions, selfcare time, etc. which all can be tracked personally so users are able to identify connections betweed tracked factors and their mood based on their personal demands.

## Current state and UI to extend

In order to do so the create mood form needs to be extended. The create create mood form consists of a wizard, currently consisting of 3 steps:

### 1:
![Image](https://github.com/krolmic/tracking_app/assets/28386738/b12101d8-8d43-4fe1-ac85-2358d0c6e1f8)

### 2:
![Image](https://github.com/krolmic/tracking_app/assets/28386738/11834188-6871-4fcd-82e7-25822b819cce)

### 3:
![Image](https://github.com/krolmic/tracking_app/assets/28386738/dc9997e1-0df1-4cd8-9c88-6e66ce6366dc)

The update mood form needs to be extended, too. Currently it's looking like this:

![Image](https://github.com/krolmic/tracking_app/assets/28386738/2fbf638d-6f7d-4763-ab81-74b303d6cd27)

Besides that the list items in the home screen need to be extended so my revenue and working hours are being shown. Current state:

![Image](https://github.com/krolmic/tracking_app/assets/28386738/ab8627cb-cbe0-4a5e-9878-b34f08fac59e)

## Technical

The mood model in the mood repository and Serverpod need to be adjusted.

## Tasks

- [x] Extend mood model in Serverpod by optional revenue and working hours, create migration
- [x] Extend mood model in the same way in the repository
- [x] Extend create mood form
- [x] Extend update mood form
- [x] Extend mood tile in the home screen
