### ISSUE TITLE
Setup app deployment

### ISSUE THREAD

**Issue by krolmic** [krolmic/tracking_app#13]
# User story

As a user I would like to use the app on my Android devices as well as on my iOS devices.

# Tasks

- [x] Setup codemagic for iOS & Android deployment
- [x] Setup sending Mails through SES
- [x] Provide encryption documentation for App Connect
- [x] App Store Product Information
- [x] Google Play Store Product Information
- [x] Release in App Store
- [ ] Release in Google Play Store
