### ISSUE TITLE
Add mood entry once per day

### ISSUE THREAD

**Issue by krolmic** [krolmic/tracking_app#14]
# User story

As user I would like to add only one mood entry per day so I can use the app to estimate my daily mood overall and assign easily earned money and worked hours to a certain day. 

# Tasks

- [x] Extend HomeMoodsState so it's saying if a mood entry has been added for today, e.g. todaysMood
- [x] Wrap AppElevatedButton with HomeCubit BlocBuilder
- [x] Show no elevated button if HomeState is initial or loading / error
- [x] Show elevated button including edit icon and label if HomeState is loaded and todaysMood is set
- [x] Show elevated button including add icon and label if HomeState is loaded and todaysMood is not set
- [x] If HomeState is loaded and todaysMood is set call `context.go('/home/update', extra: todaysMood)` on button pressed

![Image](https://github.com/krolmic/tracking_app/assets/28386738/9cd44e19-f29c-439d-96dc-c5fb62aa1949)
