### ISSUE TITLE
Calendar view

### ISSUE THREAD

**Issue by krolmic** [krolmic/tracking_app#15]
# User Story

As a user I would like to see my mood entries in a calendar view showing current month by default so I can clearly see when I tracked my mood and see all estimated mood values at once for the selected month without scrolling which is needed in the home screen list view.

# Tasks

- [x] Add calendar package enabling setting custom calendar day icons, e.g. https://pub.dev/packages/flutter_calendar_carousel
- [x] Extend Serverpod so loading mood entries by passing from and to date is possible, regenerate client
- [x] Extend mood repository after extending Serverpod
- [x] Add calendar screen, its route and additional icon in the navigation
- [x] In calendar view, load moods for the current month initially
- [x] Show moods in a calendar widget by a custom event icon showing the estimated mood
- [x] Load moods for the selected calendar month as it changes
- [x] On tap on a mood entry in the calendar, navigate to the mood update screen
