### ISSUE TITLE
Firebase Remote Config - Force Update

### ISSUE THREAD

**Issue by krolmic** [krolmic/tracking_app#150]
## User story

As a user I would like to get forced to update the app instead of using an outdated app version in case there are breaking changes.

## Subtasks

- [ ] Setup Firebase Remote Config including minVersion parameter
- [ ] Add firebase_remote_config to the app
- [ ] Add ForceUpdateScreen
- [ ] Read minVersion from Firebase Remote Config as the app is starting
- [ ] Show ForceUpdateScreen if current version is smaller than minVersion
