### ISSUE TITLE
Change years in the graph screen

### ISSUE THREAD

**Issue by krolmic** [krolmic/tracking_app#30]
As a user I would like to change the selected year in the graph screen so I am able to access and analyse data from different year than the current.

## Subtasks

- [x] Adapt _GraphHeader UI
  - [x] Add Prev & Next icon buttons
  - [x] Update layout so the year is on the left side and settings, prev, next buttons are on the rights side
- [x] Enable setting target date to prev & next year via prev & next buttons
- [x] Disable weeks in selection only for current year
- [x] Disable months in selection only for current year
- [x] Disable next button if next year is greater than current year
- [x] Add / update DateTime extension tests

## UI prototype

![Image](https://github.com/user-attachments/assets/0650e894-c32b-4127-82f2-8ace459c8b06)
